<?php

/**
 * "URI" => 120 代表该URI每分钟的允许访问频率为120次
 * 请不要修改此文件的内容
 */
$defaultRoutes = [
    "cmdb" => [
        "POST /discovery/@rule_id/_discover" => 120,
        'GET /application/search' => 120,
        'GET /application/search-all' => 120,
        'GET /application/@appId' => 120,
        'GET /applications/extra' => 120,
        'GET /cluster/list/@appId' => 120,
        'POST /cluster' => 120,
        'GET /cluster/device/@clusterId' => 120,
        'DELETE /cluster/@clusterId' => 120,
        'GET /cluster/@clusterId' => 120,
        'GET /device/search/@appId' => 120,
        'GET /device/search' => 120,
        'GET /device/app-list' => 120,
        'GET /device/@deviceId' => 120,
        'POST /device/register' => 120,
        'GET /business/search' => 120,
        'GET /business/search-link' => 120,
        'GET /business/@businessId' => 120,
        'GET /business/children/@businessId' => 120,
        'GET /business/appList/@businessId' => 120,
        'GET /object/attr/@obj' => 120,
        'GET /object/attr/@obj/@attrId' => 120,
        'POST /object/attr/@obj' => 120,
        'DELETE /object/attr/@obj/@attrId' => 120,
        'PUT /object/attr/@obj/@attrId' => 120,
        'POST /object/init' => 120,
        'GET /object/list' => 120,
        'GET /object/list/@objectId' => 1200,
        'GET /object/@objectId' => 120,
        'POST /object' => 120,
        'DELETE /object/@objectId' => 120,
        'PUT /object/@objectId' => 120,
        'GET /object/instance/attr/@objectId/@attrId' => 120,
        'GET /object/instance/list/@objectId/@instanceId' => 120,
        'GET /object/instance/list/@objectId' => 1200,
        'GET /object/instance/@objectId/@instanceId' => 120,
        'GET /object/fulltext/@key' => 120,
        'POST /object/fulltext' => 120,
        'POST /object/instance/list/@objectId' => 1200,
        'POST /object/instance/message' => 120,
        'POST /object/instance/@objectId' => 120,
        'DELETE /object/instance/fields/@objectId/@fields' => 120,
        'DELETE /object/instance/@objectId/@instanceId' => 120,
        'DELETE /object/instance/@objectId' => 120,
        'PUT /object/instance/@objectId/@instanceId' => 120,
        'PUT /object/instance/@objectId' => 120,
        'GET /agent/download/key' => 120,
        'POST /cluster/@clusterId/device/@deviceId' => 120,
        'GET /object/_ref' => 120,
        'GET /object/@object_id/instance/_ref' => 120,
        'POST /object/@object_id/instance' => 120,
        'DELETE /cluster/@clusterId/device/@deviceId' => 120,
	'POST /object/@objectId/instance/_search' => 120,
    ],
    "cmdb_resource" => [
        'GET /object/@object_id/instance' => 120,
        'GET /object/list/@objectId' => 1200,
        'GET /object/instance/list/@objectId' => 1200,
        'POST /object/instance/list/@objectId' => 1200,
	'GET /object' => 1200,
    ],
    "tools" => [
        'GET /tools/@toolId' => 120,
        'POST /tools/execution' => 120,
    ],
    "report" => [
       'POST /api/v1/custom_report' => 120,
    ],
    "auto_detect" => [
        'POST /api/v1/custom_object/report' => 120,
    ],
    "deploy" => [
        'POST /agent/transportFile/startServer' => 120,
        'GET /operation/summary/@task_id' => 120,
    ],
    "command" => [
        'GET /cmd/info/@task_id' => 120,
        'GET /cmd/task' => 120,
    ],
    "command" => [
        'GET /object/@object_id/instance' => 120,
    ],
];
